#!/usr/bin/env sh

export PATH="$HOME/.local/bin:$HOME/.local/sbin:$HOME/.local/games:$PATH"
export EDITOR="nvim"
export VISUAL="$EDITOR"
export LC_TIME="id_ID.UTF8"

export XDG_CONFIG_HOME="$HOME/.config"
export  XDG_CACHE_HOME="$HOME/.cache"
export   XDG_DATA_HOME="$HOME/.local/share"
export  XDG_STATE_HOME="$HOME/.local/state"
