#!/usr/bin/env python

fmap = { # <name>: ((<type>, <destination>, <source>),),
    'sh': (
        ('d', '.config/', 'dot/sh/.config/sh'),
        ('f', '.config/sh.d/', 'dot/sh/.config/sh.d/*'),
    ),
    'dash': (
        ('f', '.', 'dot/dash/.profile'),
    ),
    'zsh': (
        ('f', '.', 'dot/zsh/.zshrc'),
    ),
    'bash': (
        ('f', '.', 'dot/bash/.bash_logout'),
        ('f', '.', 'dot/bash/.inputrc'),
        ('f', '.', 'dot/bash/.bash_profile'),
        ('f', '.', 'dot/bash/.bashrc'),
    ),
    'fish': (
        ('f', '.config/fish/', 'dot/fish/.config/fish/config.fish'),
    ),
    'neovim': (
        ('d', '.config/', 'dot/neovim/.config/nvim'),
    ),
    'bspwm': (
        ('d', '.config/', 'dot/bspwm/.config/bspwm'),
    ),
    'mpv': (
        ('d', '.config/', 'dot/mpv/.config/mpv'),
    ),
    'fontconfig': (
        ('d', '.config/', 'dot/fontconfig/.config/fontconfig'),
    ),
    'ranger': (
        ('d', '.config/', 'dot/ranger/.config/ranger'),
        ('f', '.config/sh.d/', 'dot/ranger/.config/sh.d/*'),
    ),
    'xinit': (
        ('f', '.', 'dot/xinit/.xinitrc'),
    ),
}

_all = (
    'sh',
    'zsh',
    'dash',
    'neovim',
    'ranger',
    'mpv',
    'fontconfig',
    'bspwm'
    'xinit',
)
