#!/usr/bin/env sh

test "$(id -u)" = 0 || exec su -c "$0" "$@"

cd "$(dirname "$(realpath "$0")")" || exit 1

{
    cat cache/hosts
    test -f custom-hosts && {
        printf "\n# custom-hosts\n"
        cat custom-hosts
    }
} > /etc/hosts
