#!/usr/bin/env sh

# reset desktops
for v in $(bspc query -M --names); do
    bspc monitor "$v" -d \;a \;b \;c \;d \;e \;f \;g \;h \;i \;j \;k \;l
done

bspc config normal_border_color	  '#1f1f1f'
bspc config active_border_color   '#7f7f7f'
bspc config focused_border_color  '#ffffff'
bspc config presel_feedback_color '#1f1f1f'
v=2
bspc config window_gap -$v
bspc config border_width $v
bspc config left_padding $v
bspc config right_padding $v
bspc config top_padding $v
bspc config bottom_padding $v
bspc config click_to_focus              button1
bspc config split_ratio                 0.50
bspc config borderless_monocle          true
bspc config merge_overlapping_monitors  true
bspc config pointer_modifier            mod4
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner

bspc rule --add 'Nitrogen' state=floating
bspc rule --add 'st-passmenu' state=floating layer=above \
    follow=true sticky=true

unset v
