#!/usr/bin/env sh

if [ "$XDG_RUNTIME_DIR" ]; then
    BSPWM_TMP="$XDG_RUNTIME_DIR/bspwm"
elif [ -w '/tmp' ]; then
    BSPWM_TMP="/tmp/bspwm@$USER"
elif [ "$XDG_CACHE_HOME" ]; then
    BSPWM_TMP="$XDG_CACHE_HOME/bspwm"
else
    BSPWM_TMP="$HOME/.cache/bspwm"
fi
mkdir -p "$BSPWM_TMP" && chmod 700 "$BSPWM_TMP"

export BSPWM_TMP
export BSPWM_SOCKET="$BSPWM_TMP/socket"
export BSPWM_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"
export DESKTOP_SESSION='bspwm'

"$BSPWM_HOME/bin/background-live" &
xwallpaper --center "$HOME/Pictures/BG/black.png" &
#background-slideshow &

picom -f -D 7 &
sxhkd -t 10 -r "$BSPWM_TMP/sxhkd.log" -c "$BSPWM_HOME/sxhkdrc" &
unclutter -idle 60 -jitter 5 -root &
sleep 10 && activate-linux-run &

exec bspwm
