#!/usr/bin/env sh

export DESKTOP_SESSION='bspwm'
BSPWM_TMP="$(get-user-tmp-path bspwm)"
[ -d "$BSPWM_TMP" ] || mkdir -p "$BSPWM_TMP" && chmod 700 "$BSPWM_TMP"
export BSPWM_TMP
export BSPWM_SOCKET="$BSPWM_TMP/socket"
export BSPWM_HOME="${XDG_CONFIG_HOME:-$HOME/.config}/bspwm"

picom -f -D 7 &
background &
unclutter -idle 60 -jitter 5 -root &
sleep 5 && activate-linux &
sxhkd -t 10 -r "$BSPWM_TMP/sxhkd.log" -c "$BSPWM_HOME/sxhkdrc" &
bspwm
