#!/usr/bin/env sh

[ "$1" ] || exit

f="$BSPWM_SHARED_DIR/volume.int"
if [ -f "$f" ]; then
    if [ "$1" = '!' ]; then # toggle mute
        if [ "$(amixer sget 'Master' | grep -Eo '\[.*\%]')" = '[0%]' ]; then
            $0 '='
        else
            amixer sset 'Master' '0%' 1> /dev/null
        fi
    else # TODO use amixer sget instead
        [ "$(wc -c <"$f")" -le 3 ] && v=$(cat "$f")
        [ "$v" ] || v=50
        #[ "$1" = '=' ]
        [ "$1" = '+' ] && v=$((v + 5)) && [ "$v" -gt 100 ] && v=100
        [ "$1" = '-' ] && v=$((v - 5)) && [ "$v" -lt 0 ] && v=0
        amixer sset 'Master' "$v%" 1> /dev/null
        printf '%s' "$v" > "$f"
    fi
fi
