[manager]
ratio          = [ 0, 1, 1 ]
sort_by        = "alphabetical"
linemode       = "size"
show_hidden    = true
scrolloff      = 9
mouse_events   = []
title_format   = "yazi: {cwd}"

[opener]
noop = [ { run = ":", desc = "noop", block = true } ]
edit = [ { run = '"$EDITOR" -- "$@"', desc = "editor", block = true } ]
open = [ { run = 'xdg-open "$1"' } ]
arclist = [ { run = 'atool -l -e -- "$@" 2>&1 | "$PAGER"', desc = "list files", block = true } ]
extract = [ { run = 'ya pub extract --list "$@"', desc = "extract here" } ]
"mpv block" = [ { run = 'mpv -- "$@"', desc = "mpv block", block = true } ]
"mvi block" = [ { run = 'mvi -- "$@"', desc = "mvi block", block = true } ]
"mpv orphan" = [ { run = 'mpv -- "$@"', desc = "mpv orphan", orphan = true } ]
"mvi orphan" = [ { run = 'mvi -- "$@"', desc = "mvi orphan", orphan = true } ]

[open]
rules = [
	{ name = "*/", use = [
        "noop",
        "mpv block",
        "mvi block",
        "mpv orphan",
        "mvi orphan",
    ] },

	{ mime = "video/*", use = [ "mpv block", "mpv orphan" ] },
	{ mime = "audio/*", use = [ "mpv block", "mpv orphan" ] },
	{ mime = "image/*", use = [ "mvi block", "mvi orphan" ] },

	{ mime = "application/{,g}zip", use = [ "arclist", "extract" ] },
	{ mime = "application/x-{tar,bzip*,7z-compressed,xz,rar}", use = [ "arclist", "extract" ] },

	{ mime = "text/*", use = [ "edit" ] },
	{ mime = "inode/x-empty", use = [ "edit" ] },
	{ mime = "application/{json,x-ndjson}", use = [ "edit" ] },
	{ mime = "*/javascript", use = [ "edit" ] },

	{ name = "*", use = [ "noop", "edit", "open" ] },
]
