#!/bin/sh

for v in $(bspc query -M --names); do
    bspc monitor "$v" -d f1 f2 f3 f4 f5 f6 f7 f8 f9 fA fB fC
done

bspc config normal_border_color	  '#1f1f1f'
bspc config active_border_color   '#7f7f7f'
bspc config focused_border_color  '#ffffff'
bspc config presel_feedback_color '#1f1f1f'

v=2
bspc config border_width "$v"
bspc config window_gap "-$v"
bspc config left_padding "$v"
bspc config right_padding "$v"
bspc config top_padding "$v"
bspc config bottom_padding "$v"
unset v

bspc config borderless_monocle          true
bspc config click_to_focus              button1
bspc config ignore_ewmh_focus           true
bspc config merge_overlapping_monitors  true
bspc config pointer_action1             move
bspc config pointer_action2             resize_side
bspc config pointer_action3             resize_corner
bspc config pointer_modifier            mod4
bspc config remove_unplugged_monitors   true
bspc config single_monocle              true
bspc config split_ratio                 0.5
